// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type AcceptPaymentReq struct {
	UserId int64 `json:"user_id"`
}

type AcceptPaymentResp struct {
	Status string `json:"status"`
}

type CustomCallbackReq struct {
	Description string `json:"description"`
	PaymentSn   string `json:"paymentSn"`
	NotifyUrl   string `json:"notify_url"`
	TotalPrice  int64  `json:"total_price"`
	UserId      int64  `json:"user_id"`
}

type CustomCallbackResp struct {
	Status string `json:"status"`
}
