// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type ThirdPaymentWxPayCallbackReq struct {
}

type ThirdPaymentWxPayCallbackResp struct {
	ReturnCode string `json:"return_code"`
}

type ThirdPaymentWxPayReq struct {
	OrderSn     string `json:"orderSn"`
	ServiceType string `json:"serviceType"`
}

type ThirdPaymentWxPayResp struct {
	Status string `json:status`
}
