// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: pb/travel.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Travel_HomestayDetail_FullMethodName         = "/pb.travel/homestayDetail"
	Travel_HomestayList_FullMethodName           = "/pb.travel/homestayList"
	Travel_GuessList_FullMethodName              = "/pb.travel/guessList"
	Travel_BusinessList_FullMethodName           = "/pb.travel/businessList"
	Travel_GoodBoss_FullMethodName               = "/pb.travel/goodBoss"
	Travel_HomestayBusinessDetail_FullMethodName = "/pb.travel/homestayBusinessDetail"
	Travel_HomestayBusinessList_FullMethodName   = "/pb.travel/homestayBusinessList"
)

// TravelClient is the client API for Travel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// service
type TravelClient interface {
	// homestay
	HomestayDetail(ctx context.Context, in *HomestayDetailReq, opts ...grpc.CallOption) (*HomestayDetailResp, error)
	HomestayList(ctx context.Context, in *HomestayListReq, opts ...grpc.CallOption) (*HomestayListResp, error)
	GuessList(ctx context.Context, in *GuessListReq, opts ...grpc.CallOption) (*GuessListResp, error)
	BusinessList(ctx context.Context, in *BusinessListReq, opts ...grpc.CallOption) (*BusinessListResp, error)
	// homestay business
	GoodBoss(ctx context.Context, in *GoodBossReq, opts ...grpc.CallOption) (*GoodBossResp, error)
	HomestayBusinessDetail(ctx context.Context, in *HomestayBusinessDetailReq, opts ...grpc.CallOption) (*HomestayBusinessDetailResp, error)
	HomestayBusinessList(ctx context.Context, in *HomestayListReq, opts ...grpc.CallOption) (*HomestayBusinessListResp, error)
}

type travelClient struct {
	cc grpc.ClientConnInterface
}

func NewTravelClient(cc grpc.ClientConnInterface) TravelClient {
	return &travelClient{cc}
}

func (c *travelClient) HomestayDetail(ctx context.Context, in *HomestayDetailReq, opts ...grpc.CallOption) (*HomestayDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomestayDetailResp)
	err := c.cc.Invoke(ctx, Travel_HomestayDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *travelClient) HomestayList(ctx context.Context, in *HomestayListReq, opts ...grpc.CallOption) (*HomestayListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomestayListResp)
	err := c.cc.Invoke(ctx, Travel_HomestayList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *travelClient) GuessList(ctx context.Context, in *GuessListReq, opts ...grpc.CallOption) (*GuessListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuessListResp)
	err := c.cc.Invoke(ctx, Travel_GuessList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *travelClient) BusinessList(ctx context.Context, in *BusinessListReq, opts ...grpc.CallOption) (*BusinessListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BusinessListResp)
	err := c.cc.Invoke(ctx, Travel_BusinessList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *travelClient) GoodBoss(ctx context.Context, in *GoodBossReq, opts ...grpc.CallOption) (*GoodBossResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodBossResp)
	err := c.cc.Invoke(ctx, Travel_GoodBoss_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *travelClient) HomestayBusinessDetail(ctx context.Context, in *HomestayBusinessDetailReq, opts ...grpc.CallOption) (*HomestayBusinessDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomestayBusinessDetailResp)
	err := c.cc.Invoke(ctx, Travel_HomestayBusinessDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *travelClient) HomestayBusinessList(ctx context.Context, in *HomestayListReq, opts ...grpc.CallOption) (*HomestayBusinessListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomestayBusinessListResp)
	err := c.cc.Invoke(ctx, Travel_HomestayBusinessList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TravelServer is the server API for Travel service.
// All implementations must embed UnimplementedTravelServer
// for forward compatibility.
//
// service
type TravelServer interface {
	// homestay
	HomestayDetail(context.Context, *HomestayDetailReq) (*HomestayDetailResp, error)
	HomestayList(context.Context, *HomestayListReq) (*HomestayListResp, error)
	GuessList(context.Context, *GuessListReq) (*GuessListResp, error)
	BusinessList(context.Context, *BusinessListReq) (*BusinessListResp, error)
	// homestay business
	GoodBoss(context.Context, *GoodBossReq) (*GoodBossResp, error)
	HomestayBusinessDetail(context.Context, *HomestayBusinessDetailReq) (*HomestayBusinessDetailResp, error)
	HomestayBusinessList(context.Context, *HomestayListReq) (*HomestayBusinessListResp, error)
	mustEmbedUnimplementedTravelServer()
}

// UnimplementedTravelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTravelServer struct{}

func (UnimplementedTravelServer) HomestayDetail(context.Context, *HomestayDetailReq) (*HomestayDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomestayDetail not implemented")
}
func (UnimplementedTravelServer) HomestayList(context.Context, *HomestayListReq) (*HomestayListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomestayList not implemented")
}
func (UnimplementedTravelServer) GuessList(context.Context, *GuessListReq) (*GuessListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GuessList not implemented")
}
func (UnimplementedTravelServer) BusinessList(context.Context, *BusinessListReq) (*BusinessListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BusinessList not implemented")
}
func (UnimplementedTravelServer) GoodBoss(context.Context, *GoodBossReq) (*GoodBossResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoodBoss not implemented")
}
func (UnimplementedTravelServer) HomestayBusinessDetail(context.Context, *HomestayBusinessDetailReq) (*HomestayBusinessDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomestayBusinessDetail not implemented")
}
func (UnimplementedTravelServer) HomestayBusinessList(context.Context, *HomestayListReq) (*HomestayBusinessListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HomestayBusinessList not implemented")
}
func (UnimplementedTravelServer) mustEmbedUnimplementedTravelServer() {}
func (UnimplementedTravelServer) testEmbeddedByValue()                {}

// UnsafeTravelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TravelServer will
// result in compilation errors.
type UnsafeTravelServer interface {
	mustEmbedUnimplementedTravelServer()
}

func RegisterTravelServer(s grpc.ServiceRegistrar, srv TravelServer) {
	// If the following call pancis, it indicates UnimplementedTravelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Travel_ServiceDesc, srv)
}

func _Travel_HomestayDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomestayDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TravelServer).HomestayDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Travel_HomestayDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TravelServer).HomestayDetail(ctx, req.(*HomestayDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Travel_HomestayList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomestayListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TravelServer).HomestayList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Travel_HomestayList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TravelServer).HomestayList(ctx, req.(*HomestayListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Travel_GuessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuessListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TravelServer).GuessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Travel_GuessList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TravelServer).GuessList(ctx, req.(*GuessListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Travel_BusinessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusinessListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TravelServer).BusinessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Travel_BusinessList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TravelServer).BusinessList(ctx, req.(*BusinessListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Travel_GoodBoss_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodBossReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TravelServer).GoodBoss(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Travel_GoodBoss_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TravelServer).GoodBoss(ctx, req.(*GoodBossReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Travel_HomestayBusinessDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomestayBusinessDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TravelServer).HomestayBusinessDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Travel_HomestayBusinessDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TravelServer).HomestayBusinessDetail(ctx, req.(*HomestayBusinessDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Travel_HomestayBusinessList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomestayListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TravelServer).HomestayBusinessList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Travel_HomestayBusinessList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TravelServer).HomestayBusinessList(ctx, req.(*HomestayListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Travel_ServiceDesc is the grpc.ServiceDesc for Travel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Travel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.travel",
	HandlerType: (*TravelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "homestayDetail",
			Handler:    _Travel_HomestayDetail_Handler,
		},
		{
			MethodName: "homestayList",
			Handler:    _Travel_HomestayList_Handler,
		},
		{
			MethodName: "guessList",
			Handler:    _Travel_GuessList_Handler,
		},
		{
			MethodName: "businessList",
			Handler:    _Travel_BusinessList_Handler,
		},
		{
			MethodName: "goodBoss",
			Handler:    _Travel_GoodBoss_Handler,
		},
		{
			MethodName: "homestayBusinessDetail",
			Handler:    _Travel_HomestayBusinessDetail_Handler,
		},
		{
			MethodName: "homestayBusinessList",
			Handler:    _Travel_HomestayBusinessList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/travel.proto",
}
