// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	homestayBussiness_ "home-nest/app/travel/cmd/api/internal/handler/homestayBussiness_"
	homestay_ "home-nest/app/travel/cmd/api/internal/handler/homestay_"
	"home-nest/app/travel/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// good boss
				Method:  http.MethodGet,
				Path:    "/homestayBussiness/goodBoss",
				Handler: homestayBussiness_.GoodBossHandler(serverCtx),
			},
			{
				// boss detail
				Method:  http.MethodGet,
				Path:    "/homestayBussiness/homestayBussinessDetail",
				Handler: homestayBussiness_.HomestayBussinessDetailHandler(serverCtx),
			},
			{
				// business list
				Method:  http.MethodGet,
				Path:    "/homestayBussiness/homestayBussinessList",
				Handler: homestayBussiness_.HomestayBussinessListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/travel/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// boss's all homestay room
				Method:  http.MethodGet,
				Path:    "/homestay/businessList",
				Handler: homestay_.BusinessListHandler(serverCtx),
			},
			{
				// guess your favorite homestay room
				Method:  http.MethodGet,
				Path:    "/homestay/guessList",
				Handler: homestay_.GuessListHandler(serverCtx),
			},
			{
				// homestay room detail
				Method:  http.MethodGet,
				Path:    "/homestay/homestayDetail",
				Handler: homestay_.HomestayDetailHandler(serverCtx),
			},
			{
				// homestay room list
				Method:  http.MethodGet,
				Path:    "/homestay/homestayList",
				Handler: homestay_.HomestayListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/travel/v1"),
	)
}
